Prefix all template parameters with "drawio"
after the NC14 update the parameter "theme" is used by NC itself,
causing an:
	Error: Call to a member function getTitle() on string

This prefixes all custom template params with "drawio" to prevent this
kind of errors in the future.

Signed-off-by: Jan Losinski <losinski@wh2.tu-dresden.de>